### ISSUE TITLE
Expose deployed workflows as MCP tools through a cmd/cleat-mcp proxy, gated by exposure classes

### ISSUE THREAD

**Issue by rcownie** [cleat-team/cleat#1982]
**Owner decisions, 2026-09-22:**
- Workflows are exposed as MCP tools through a separate `cmd/cleat-mcp` binary **in this repo**, which proxies cleat's existing HTTP API.
- **Exposure is gated by exposure classes**, the designed-but-unbuilt `public` / `auth` / `internal` classes. So this is **blocked** on those being built.
- Auth: the MVP passes through the credentials the cleat API already accepts. OAuth 2.1 resource-server mode, validating tokens from the configured OIDC issuer, is phase 2.
- **Every workflow tool is annotated as having side effects**, using MCP's standard tool annotations, so the client's confirmation prompt applies. Starting a workflow from a model's output is a prompt-injection surface.

## Status: blocked

Blocked on exposure classes. That design is in cleat-internal `per-tenant-middleware-design-2026-09-18.md`, in the revision "the field says this is an exposure class". It has no cleat issue yet. MCP exposes only workflows whose class permits it; the class decides which callers may see a tool at all.

It also benefits from the typed-invocation schema issue (#1980), which supplies real `inputSchema`s. That is not blocking: the MVP can use `{"type":"object"}` passthrough.

## Design

| MCP | cleat |
|---|---|
| `tools/list` | deployed definitions whose exposure class admits this caller, scoped to the caller's tenant (`tools/list` may vary by authorisation) |
| `tools/call` | `POST /api/workflows/{name}/start`, with an idempotency key the proxy derives per MCP request, so a client retry does not start a second run |
| task id | run id |
| task working / completed / failed | run status, using the settled-status definitions in #1979 |
| task `input_required` | run waiting on a signal or promise (phase 2) |
| cancel | `POST /api/workflows/{id}/cancel` |

**Reads:** only the status of runs this MCP session started. General browsing of runs is a read API, and read APIs are declined (Tier C). So no MCP `resources` in scope.

**Not in scope:**
- A workflow *calling* MCP tools. That would be a separate `mcpclient` plugin.
- Elicitation.

**Before implementation:** verify the current MCP spec version, the Tasks extension's shape, and the tool-annotation names against the spec itself. The design notes' versions came from an agent and are unverified.

## Acceptance

- An MCP client (e.g. the MCP Inspector) can list and call an exposed workflow, get its result, and cancel it.
- A workflow in a non-exposed class never appears in `tools/list`, and calling it by name fails.
- A retried `tools/call` starts exactly one run.

No guest or SDK change; R7 is untouched.

Design context: cleat-internal `design-options-2026-09-22.md` §1.

**Comment by rcownie** [comment]
Blocked on #1986 (exposure classes), now filed with the owner's decisions of 2026-09-22.
