### ISSUE TITLE
The web/ dependabot PRs cannot pass individually: svelte-check predates TS 7, jsdom 30 skews with undici, and Web Dashboard is not a required check

### ISSUE THREAD

**Issue by rcownie** [cleat-team/cleat#1709]
Three dependabot PRs against `web/` fail for two distinct upstream reasons, and a fourth conflicts. None of them can go green alone, because the `web/` toolchain has to move as a set.

## #1357 — typescript 5.5.4 -> 7.0.2

`Web Dashboard` runs `npm run check`, which is `svelte-check --tsconfig ./tsconfig.json`. Under TypeScript 7 it throws before checking anything:

```
/home/runner/work/cleat/cleat/web/node_modules/svelte-check/dist/src/index.js:14971
TypeError: Cannot read properties of undefined (reading 'useCaseSensitiveFileNames')
##[error]Process completed with exit code 1.
```

develop pins `svelte-check` 4.4.8. The failure is inside svelte-check's own bundle, reaching for a TypeScript compiler-API surface that TS 7 no longer presents. So #1357 is blocked on svelte-check, not on anything in this repo: it needs a svelte-check release that supports TS 7, and until one exists the PR cannot pass.

## #1359 — jsdom 25.0.1 -> 30.0.1

Here `svelte-check` passes (`0 errors and 16 warnings in 3 files`) and vitest dies instead:

```
Vitest caught 7 unhandled errors during the test run.
Error: [vitest-pool]: Failed to start forks worker for test files .../web/src/lib/cost.test.ts
Caused by: TypeError: webidl.util.markAsUncloneable is not a function
```

develop's lockfile has no `undici` at all — jsdom 25 does not pull one. #1359's lockfile adds `"undici": "^8.9.0"` and resolves `undici` 8.10.2. The error names the missing API; which side owns it (jsdom 30.0.1 calling an undici surface that 8.10.2 no longer exports, or a too-loose range) is the thing to check upstream rather than assume from the message.

## #1358 — vitest 4.1.11 -> 5.0.0

This one is **not failing**. 40 pass, 3 skipping, `mergeable: MERGEABLE`, and every one of the 32 required contexts reports success. It is stalled by whatever makes it `BLOCKED`, which is a separate matter — see #1688, where I have recorded that the cancelled-twin explanation does not fit this PR.

## #1355 — npm-minor-and-patch group

`DIRTY`. It conflicts, and a rebase in place made it worse once already (three more run sets, all 18 runs cancelled). It should be recreated rather than rebased.

## The shape of it

`Web Dashboard` is **not** a required status check (0 hits against the 32 required contexts), so these dashboard failures do not themselves block a merge — they make the PRs `UNSTABLE`. That is worth saying plainly, because it means the current state is "we can merge PRs that break the dashboard", which is a worse position than being blocked by them.

The four PRs are not four independent bumps. typescript, svelte-check, vitest, jsdom and undici are one dependency graph, and dependabot is proposing to move corners of it one at a time. Two of the four cannot pass in isolation at any point in the future — they need a companion bump dependabot will not group with them.

## Options

1. **One coordinated `web/` upgrade PR**, moving typescript, svelte-check, vitest, jsdom and whatever undici resolves to, together; close #1355/#1357/#1359 in favour of it. #1358 is green and can go on its own.
2. **Group them in dependabot config** so `web/` devDependencies are proposed as a single PR, and this stops recurring.
3. **Hold #1357 specifically** until svelte-check supports TS 7 — it is not actionable here regardless of which of the above is chosen.

(2) is the durable half and composes with either of the others.

Whichever is chosen, `Web Dashboard` being non-required is a separate decision worth making deliberately rather than inheriting.

## Verification

- `gh run view --repo cleat-team/cleat --job 103550687010 --log` — #1357's svelte-check throw.
- `gh run view --repo cleat-team/cleat --job 103550719380 --log` — #1359's `markAsUncloneable`.
- `git show origin/develop:web/package-lock.json` — svelte-check 4.4.8, typescript 5.5.4, vitest 4.1.11, jsdom 25.0.1, no undici.
- `gh pr diff 1359 --repo cleat-team/cleat | grep undici` — `"undici": "^8.9.0"`, resolved 8.10.2.
- `gh api repos/cleat-team/cleat/branches/develop/protection --jq '.required_status_checks.contexts[]' | grep -c '^Web Dashboard$'` — 0.

Claude-Session: https://claude.ai/code/session_01UbTiXNC2rGrEbBheCUkd57
